# Generated by Django 5.0.1 on 2025-11-06 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("cerere_noua", "New Buddy Request"),
                            ("cerere_acceptata", "Request Accepted"),
                            ("cerere_refuzata", "Request Rejected"),
                            ("sesiune_reminder", "Session Reminder"),
                            ("rating_nou", "New Rating Received"),
                            ("achievement_unlocked", "Achievement Unlocked"),
                            ("follow_nou", "New Follower"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titlu", models.CharField(max_length=200)),
                ("mesaj", models.TextField()),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate when clicked",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("citit", models.BooleanField(default=False)),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
                ("data_citire", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-data_creare"],
            },
        ),
    ]
