# Generated by Django 5.0.1 on 2025-11-06 21:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Goal name", max_length=100)),
                ("description", models.TextField(help_text="Goal description")),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weekly_workouts", "Weekly Workouts"),
                            ("workout_streak", "Workout Streak"),
                            ("new_gyms", "Visit New Gyms"),
                            ("social", "Social Engagement"),
                            ("custom", "Custom Goal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom Period"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.IntegerField(
                        help_text="Target number to achieve (e.g., 3 workouts)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🎯",
                        help_text="Emoji or icon identifier",
                        max_length=50,
                    ),
                ),
                (
                    "xp_reward",
                    models.IntegerField(
                        default=20, help_text="XP awarded on completion"
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=7, help_text="Duration in days for custom periods"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this goal template active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Goal Template",
                "verbose_name_plural": "Goal Templates",
                "ordering": ["goal_type", "target_value"],
            },
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_value",
                    models.IntegerField(default=0, help_text="Current progress"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("deadline", models.DateTimeField(help_text="Goal deadline")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_streak",
                    models.IntegerField(default=0, help_text="Current streak count"),
                ),
                (
                    "last_streak_date",
                    models.DateField(
                        blank=True,
                        help_text="Last day streak was maintained",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_goals",
                        to="goals.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Goal",
                "verbose_name_plural": "User Goals",
                "ordering": ["-created_at"],
            },
        ),
    ]
