# Generated by Django 5.0.1 on 2025-11-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="feedback",
            field=models.CharField(
                blank=True,
                help_text="Feedback scurt (max 50 caractere)",
                max_length=50,
                null=True,
            ),
        ),
    ]
