# Generated by Django 5.0.1 on 2025-11-06 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Achievement name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What user needs to do to unlock this"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏆",
                        help_text="Emoji or icon identifier",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workout", "Workout"),
                            ("social", "Social"),
                            ("exploration", "Exploration"),
                            ("special", "Special"),
                        ],
                        default="workout",
                        max_length=20,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for code (e.g., 'first_workout')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "required_count",
                    models.IntegerField(
                        default=1, help_text="How many times action needs to happen"
                    ),
                ),
                (
                    "xp_reward",
                    models.IntegerField(default=10, help_text="XP points awarded"),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["category", "required_count"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Current progress towards achievement"
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_by",
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
