# Generated by Django 5.0.1 on 2025-11-06 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sesiune",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tip_antrenament",
                    models.CharField(
                        help_text="Ex: Cardio, Forță, CrossFit, etc.", max_length=100
                    ),
                ),
                (
                    "interval_orar",
                    models.CharField(help_text="Ex: 18:00 - 20:00", max_length=100),
                ),
                (
                    "descriere",
                    models.TextField(
                        blank=True,
                        help_text="Descriere opțională a sesiunii",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activ", "Activ"),
                            ("expirat", "Expirat"),
                            ("arhivat", "Arhivat"),
                        ],
                        default="activ",
                        max_length=20,
                    ),
                ),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
                (
                    "data_expirare",
                    models.DateTimeField(
                        help_text="Sesiunea devine expirată după această dată"
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiuni",
                        to="gyms.sala",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiuni",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesiune de Antrenament",
                "verbose_name_plural": "Sesiuni de Antrenament",
                "ordering": ["-data_creare"],
            },
        ),
        migrations.CreateModel(
            name="Cerere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "În așteptare"),
                            ("acceptat", "Acceptat"),
                            ("refuzat", "Refuzat"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
                ("data_raspuns", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cereri_trimise",
                        to="users.userprofile",
                    ),
                ),
                (
                    "sesiune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cereri",
                        to="workouts.sesiune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cerere Gym Buddy",
                "verbose_name_plural": "Cereri Gym Buddy",
                "ordering": ["-data_creare"],
                "unique_together": {("sesiune", "applicant")},
            },
        ),
    ]
