# Generated by Django 5.0.1 on 2025-11-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesiune",
            name="status",
            field=models.CharField(
                choices=[
                    ("activ", "Activ"),
                    ("expirat", "Expirat"),
                    ("arhivat", "Arhivat"),
                    ("completat", "Completat"),
                    ("anulat", "Anulat"),
                ],
                default="activ",
                max_length=20,
            ),
        ),
    ]
