# Generated by Django 5.0.1 on 2025-11-06 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_poza_userprofile_avatar_and_more"),
        ("workouts", "0002_alter_sesiune_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesiune",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Oraș unde are loc sesiunea",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sesiune",
            name="data_sesiune",
            field=models.DateTimeField(
                blank=True, help_text="Data și ora sesiunii", null=True
            ),
        ),
        migrations.AddField(
            model_name="sesiune",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Poză sesiune", null=True, upload_to="sessions/"
            ),
        ),
        migrations.AddField(
            model_name="sesiune",
            name="max_participants",
            field=models.IntegerField(
                default=5, help_text="Număr maxim de participanți"
            ),
        ),
        migrations.AddField(
            model_name="sesiune",
            name="private",
            field=models.BooleanField(
                default=False, help_text="Sesiune privată (doar pentru prieteni)"
            ),
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sesiune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="workouts.sesiune",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participated_sessions",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant Sesiune",
                "verbose_name_plural": "Participanți Sesiuni",
                "ordering": ["joined_at"],
                "unique_together": {("sesiune", "user")},
            },
        ),
    ]
