# Generated by Django 5.0.1 on 2025-11-06 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                (
                    "poza",
                    models.URLField(
                        blank=True, help_text="URL către poza de profil", null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="Rating mediu 1-5 stele",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "nr_antrenamente",
                    models.IntegerField(
                        default=0, help_text="Număr total de antrenamente completate"
                    ),
                ),
                (
                    "grad",
                    models.CharField(
                        choices=[
                            ("Începător", "Începător"),
                            ("Intermediar", "Intermediar"),
                            ("Avansat", "Avansat"),
                            ("Sportiv", "Sportiv"),
                            ("Expert", "Expert"),
                            ("Veteran", "Veteran"),
                        ],
                        default="Începător",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilizator",
                "verbose_name_plural": "Profile Utilizatori",
            },
        ),
    ]
