# Generated by Django 5.0.1 on 2025-11-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="poza",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Poza de profil", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Bio scurt (max 140 caractere)",
                max_length=140,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True, help_text="Oraș", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(
                default=0, help_text="Număr de zile consecutive cu antrenament"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_workout_date",
            field=models.DateField(
                blank=True, help_text="Data ultimului antrenament completat", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Număr de telefon", max_length=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Motiv blocare", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to="users.userprofile",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_users",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilizator Blocat",
                "verbose_name_plural": "Utilizatori Blocați",
                "ordering": ["-created_at"],
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
