# Generated by Django 5.0.1 on 2025-11-06 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nume",
                    models.CharField(
                        help_text="Numele sălii de fitness", max_length=200
                    ),
                ),
                (
                    "adresa",
                    models.CharField(
                        help_text="Adresa completă a sălii", max_length=300
                    ),
                ),
                (
                    "latitudine",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitudine pentru hartă",
                        max_digits=9,
                    ),
                ),
                (
                    "longitudine",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitudine pentru hartă",
                        max_digits=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sala de Fitness",
                "verbose_name_plural": "Săli de Fitness",
                "ordering": ["nume"],
            },
        ),
    ]
