# Generated by Django 5.0.1 on 2025-11-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="descriere",
            field=models.TextField(
                blank=True, help_text="Descriere detaliată a sălii", null=True
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="facilitati",
            field=models.TextField(
                blank=True, help_text="Listă de facilități disponibile", null=True
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="oras",
            field=models.CharField(
                blank=True,
                help_text="Orașul unde se află sala",
                max_length=100,
                null=True,
            ),
        ),
    ]
